# BEGIN_KITTY_THEME
# Base16 Lavander 
include base16-lavander.conf
# END_KITTY_THEME

# Font
font_family Maple Mono NF
font_size 18
text_composition_strategy legacy

background_opacity 1.0

confirm_os_window_close 0

# Cursor
cursor_blink_interval 0
cursor_shape block

input_delay 0
repaint_delay 2
resize_draw_strategy scale
shell_integration enabled no-cursor

# Tab bar 
tab_bar_align right
tab_bar_edge top
tab_bar_style custom
tab_separator  " "
tab_title_template "{tab.active_exe}"
tab_bar_min_tabs 2

tab_bar_margin_height 4.0 0.0
tab_bar_margin_color #030303

active_tab_foreground   #030303
active_tab_background   #696969
active_tab_font_style   bold
inactive_tab_foreground #696969
inactive_tab_background #121212
inactive_tab_font_style normal

update_check_interval 0
window_padding_width 0

enable_audio_bell no

allow_remote_control socket-only
listen_on unix:/tmp/mykitty

# Keymaps
map ctrl+f launch --type=overlay zsh -ic "~/scripts/tmux-session-dispensary.sh"
