[Launcher]
appUsage="{\"thunar\":2,\"audacity\":1,\"kitty\":1,\"nvim\":1,\"dev.zed.Zed\":15,\"helium\":11,\"legacy_launcher\":4,\"thunar-bulk-rename\":1,\"LocalSend\":11,\"firefox\":8,\"org.pwmt.zathura\":6,\"org.qutebrowser.qutebrowser\":10,\"zen-beta\":3,\"librewolf\":5,\"foot\":10,\"gvim\":1,\"qalculate-gtk\":1,\"brave-browser\":2,\"blueman-adapters\":1,\"blueman-manager\":15,\"org.pulseaudio.pavucontrol\":2,\"nwg-look\":6,\"Alacritty\":1,\"yazi\":1}"
hiddenApps=
isGridView=false
wallpaperMediaFilter=all

[Theme]
isDark=true
