[Launcher]
appUsage="{\"thunar\":2,\"audacity\":1,\"kitty\":1,\"nvim\":1,\"dev.zed.Zed\":13,\"helium\":11,\"legacy_launcher\":1,\"thunar-bulk-rename\":1,\"LocalSend\":5,\"firefox\":3,\"org.pwmt.zathura\":6,\"org.qutebrowser.qutebrowser\":10,\"zen-beta\":2,\"librewolf\":5}"
hiddenApps=
isGridView=false
wallpaperMediaFilter=all

[Theme]
isDark=true
