{
  # This is a Nix flake. A flake describes an input (where to fetch code from)
  # and an output (what to build — a NixOS config in this case).
  description = "k4rkie's NixOS configuration";

  # `inputs` declares where external code comes from.
  # nixpkgs is the main package repository — the entire NixOS ecosystem.
  inputs = {
    # `nixpkgs.url` tells Nix where to download nixpkgs from.
    # "github:NixOS/nixpkgs/nixos-26.05" means:
    # - fetch from GitHub, repo NixOS/nixpkgs
    # - use the branch "nixos-26.05" (the current stable release)
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";

    home-manager = {
      url = "github:nix-community/home-manager/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    stylix = {
      url = "github:nix-community/stylix/release-26.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # `outputs` is a function that takes the declared inputs and returns
  # something Nix can build — here, a NixOS configuration.
  # The `self` argument refers to this flake itself (this folder).
  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      stylix,
      zen-browser,
      ...
    }:
    {

      # `nixosConfigurations` is the key NixOS output.
      # You can have multiple machines here, each with its own hostname.
      # The attribute name (e.g. "nixos") becomes the name you pass to
      # `--flake .#nixxer`.
      nixosConfigurations.nixxer = nixpkgs.lib.nixosSystem {

        # The system architecture (x86_64 is typical for Intel/AMD).
        system = "x86_64-linux";

        # create an arg to then use it in configuration.nix
        specialArgs = { inherit zen-browser; };

        # `modules` is a list of NixOS module files or inline modules.
        # Each module is a function like `{ config, pkgs, ... }: { ... }`.
        modules = [
          stylix.nixosModules.stylix
          home-manager.nixosModules.home-manager
          # This pulls in the hardware config (filesystem mounts, CPU, etc.)
          # generated by nixos-generate-config.
          ./hardware-configuration.nix
          # This is the main config — all the packages, services, users, etc.
          ./configuration.nix
          {
            # Per-user Home Manager config
            home-manager.users.k4rkie = import ./home.nix;

            # Disable Stylix targets that you manage manually
            home-manager.sharedModules = [
              {
                stylix.targets.hyprland.enable = false;
                stylix.targets.waybar.enable = false;
                stylix.targets.neovim.enable = false;
              }
            ];
          }
        ];
      };
    };
}
