# ─── Tray / System ───
exec-once=blueman-applet

# ─── Shell / Bar / Notifications / OSD ───
exec-once=quickshell
exec-once=waybar
exec-once=swaync
exec-once=swayosd-server
exec-once=awww-daemon
exec-once=foot --server

# ─── Idle daemon ───
exec-once=~/scripts/idle-handler.sh
# ─── Notification helper ───
exec-once=/home/k4rkie/scripts/mpd-notify.sh

# ─── Clipboard history ───
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

# ─── Wallpaper ───
exec-once=sh -c 'sleep 0.5 && ~/scripts/wallpaper-restore.sh'

# ─── Night light ───
exec-once=wlsunset -l 27.7006 -L 83.4484 -t 3800 -T 6500
