# ─── Tag Rules ───
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

# ─── Window Rules (Float + Size) ───
windowrule=isfloating:1,width:1000,height:650,appid:pavucontrol
windowrule=isfloating:1,width:1200,height:800,appid:blueman-manager
windowrule=isfloating:1,appid:qalculate
windowrule=isfloating:1,appid:imv
windowrule=isfloating:1,width:1200,height:800,appid:rmpc
windowrule=isfloating:1,width:1200,height:840,appid:btop
windowrule=isfloating:1,width:1200,height:800,appid:xdg-desktop-portal-gtk
windowrule=isfloating:1,width:1250,height:800,appid:qalculate-gtk
windowrule=isfloating:1,width:1250,height:800,appid:com.gabm.satty

# ─── Browser -> Tag 1, opaque ───
windowrule=tags:2,focused_opacity:1,unfocused_opacity:1,appid:zen-beta
windowrule=tags:2,focused_opacity:1,unfocused_opacity:1,appid:firefox

# ─── mpv: opaque + no effects ───
windowrule=focused_opacity:1,unfocused_opacity:1,noblur:1,isnoshadow:1,appid:mpv

# ─── Layer Rules ───
# layerrule=noblur:1,noanim:1,layer_name:swaync-notification-window
layerrule=noblur:1,layer_name:swaync-control-center
# layerrule=noblur:1,noanim:1,layer_name:swayosd
