bind b set -g status
bind r source-file "~/.tmux.conf"
bind t popup -h 80% -w 80% -E $SHELL

set -g prefix C-Space
set -g base-index 1
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=#030303"
set -g window-status-current-style "fg=#5b8282"
set -g status-right "#S"
set -g status-left ""
set -g mouse on
setw -g mode-keys vi

set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

bind-key -r f run-shell "tmux neww ~/dotfiles/scripts/scripts/tmux-session-dispensary.sh"
