
# ~/.tmux.conf

# TPM plugin list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'       # minimal status plugin
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# continuum settings
set -g @continuum-restore 'off'

# minimal-tmux-status settings (you can tweak these)
set -g @minimal-tmux-fg "#111111"
set -g @minimal-tmux-bg "#96bddb"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

set -g @minimal-tmux-right false
set -g @minimal-tmux-left false

set -g status-right "#[align=right] #S "

# You can add a toggle for the status bar
bind-key b set-option status

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Set prefix to Ctrl-Space
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# TPM initialization (this must go at the end of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
