bind b set -g status
bind r source-file "~/.tmux.conf"
bind t popup -h 80% -w 80% -E $SHELL

set -g prefix C-Space
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=#030303,fg=#969696"

# Set current window color directly inside current-format instead
set -g window-status-current-style ""

# Clear out left and right sides
set -g status-left ""
set -g status-right ""

set -g mouse on
setw -g mode-keys vi

# Format inactive windows
set -g window-status-format "#{?window_start_flag,#[fg=#969696] #S : ,}#[fg=#969696]#I:#W"

# Format active window (keeps #S | white, turns #I:#W purple)
set -g window-status-current-format "#{?window_start_flag,#[fg=#969696] #S : ,}#[fg=#7D719F]#I:#W"

set -sg escape-time 0

set -g allow-passthrough on
set -ga terminal-overrides ",*:extended-keys@"
set -as terminal-features ",*:extended-keys"

if-shell '[ "$TERM" = "xterm-kitty" ]' {
    set -g default-terminal "xterm-kitty"
    set -ga terminal-overrides ",xterm-kitty:Tc"
}

set -g visual-activity off
set-option -g focus-events on

bind -n C-BSpace send-keys C-w

bind-key -r f run-shell "tmux neww ~/scripts/tmux-session-dispensary.sh"
