bind b set -g status
bind r source-file "~/.tmux.conf"
bind t popup -h 80% -w 80% -E $SHELL

set -g prefix C-Space
set -g base-index 1
set -g renumber-windows on
set -g status-position top
set -g status-style "bg=#030303,fg=#969696"

# Set current window color directly inside current-format instead
set -g window-status-current-style ""

# Clear out left and right sides
set -g status-left ""
set -g status-right ""

set -g mouse on
setw -g mode-keys vi

# Push window tabs to the right (options: left, centre, right)
set -g status-justify right

# Session block on the far left
set -g status-left "#[fg=#696969,bg=#030303,bold][#S] #[bg=default]"
set -g status-left-length 50

# Clear the right side so it doesn't crowd the windows
set -g status-right ""

# Window components
set -g window-status-format "#[fg=#696969,bg=#030303]#I:#W#[bg=default]"
set -g window-status-current-format "#[fg=#82709c,bg=#030303]#I:#W*#[bg=default]"


set -sg escape-time 0

set -g visual-activity off
set-option -g focus-events on

bind-key -r f run-shell "tmux neww ~/scripts/tmux-session-dispensary.sh"

