return {
  require("plugins.base16"),
  require("plugins.ibl"),
  require("plugins.treesitter"),
  require("plugins.autopairs"),
  require("plugins.lsp"),
  require("plugins.flash"),
  require("plugins.surround"),
  require("plugins.webdevicons"),
  require("plugins.colorhighlight"),
  require("plugins.telescope"),
  require("plugins.oil"),
  require("plugins.rendermarkdown"),
  require("plugins.conform"),
  require("plugins.luasnip"),
  require("plugins.compile-mode"),
}
