return {
  require("plugins.base16"),
  -- require("plugins.tokyonight"),
  require("plugins.lualine"),
  require("plugins.treesitter"),
  require("plugins.autopairs"),
  require("plugins.lsp"),
  require("plugins.flash"),
  require("plugins.surround"),
  require("plugins.webdevicons"),
  require("plugins.colorhighlight"),
  require("plugins.telescope"),
  require("plugins.oil"),
  require("plugins.rendermarkdown"),
  require("plugins.conform"),
  require("plugins.luasnip"),
  require("plugins.markdownpreview"),
  require("plugins.terminal"),
}
