return {
    require("plugins.jellybeans"),
    require("plugins.lualine"),
    require("plugins.treesitter"),
    require("plugins.base16"),
    require("plugins.autopairs"),
    require("plugins.lsp"),
    require("plugins.flash"),
    require("plugins.markdownrender"),
    require("plugins.surround"),
    require("plugins.toggle-term"),
    require("plugins.webdevicons"),
    require("plugins.colorhighlight"),
    require("plugins.harpoon"),
    require("plugins.neotree"),
    require("plugins.telescope"),
}
