[Launcher]
appUsage="{\"thunar\":2,\"audacity\":1,\"kitty\":1,\"nvim\":1,\"dev.zed.Zed\":5,\"helium\":4,\"legacy_launcher\":1,\"thunar-bulk-rename\":1}"
hiddenApps=
isGridView=false
wallpaperMediaFilter=all
