# vim:ft=kitty

## name:     base16 Dark Lavander
## author:   k4rkie
## license:  MIT
## upstream: https://github.com/tinted-theming/tinted-kitty
## blurb:    Dark Lavander

# Scheme name: base16 Dark Lavander
# Scheme author: k4rkie
# Template author: Tinted Theming (https://github.com/tinted-theming/tinted-kitty)

# The basic colors
background #030303
foreground #c1c1c1
selection_background #333333
selection_foreground #c1c1c1

# Cursor colors
cursor #c1c1c1
cursor_text_color #030303

# URL underline color when hovering with mouse
url_color #999999

# Kitty window border colors
active_border_color #333333
inactive_border_color #080808

# OS Window titlebar colors
wayland_titlebar_color #030303
macos_titlebar_color #030303

# Tab bar colors
active_tab_background #030303
active_tab_foreground #c1c1c1
inactive_tab_background #080808
inactive_tab_foreground #999999
tab_bar_background #080808

# The 16 terminal colors
# normal
color0 #030303
color1 #7d718f
color2 #d9af82
color3 #e78a53
color4 #696969
color5 #999999
color6 #aaaaaa
color7 #c1c1c1

# bright
color8 #121212
color9 #7d718f
color10 #d9af82
color11 #e78a53
color12 #696969
color13 #999999
color14 #aaaaaa
color15 #c1c1c1

# extended base16 colors
color16 #aaaaaa
color17 #444444
color18 #080808
color19 #121212
color20 #999999
color21 #999999
