# BlackMetal (Updated)
# Based on your new nvim colorscheme mapping

selection_foreground #080808
selection_background #888888

foreground #888888
background #080808

# Standard colors
color0   #080808
color1   #5f8787
color2   #fbcb97
color3   #e78a53
color4   #888888
color5   #999999
color6   #aaaaaa
color7   #c1c1c1

# Bright colors
color8   #333333
color9   #5f8787
color10  #fbcb97
color11  #e78a53
color12  #888888
color13  #999999
color14  #aaaaaa
color15  #c1c1c1

active_tab_foreground #888888
active_tab_background #080808
inactive_tab_foreground #666666
inactive_tab_background #080808

active_border_color #888888
