font_family     FiraCode Nerd Font
font_size 15.0
text_composition_strategy legacy

cursor_shape block

#--Cursor Trail--
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.05 0.20
    
shell_integration enabled no-cursor
window_padding_width 0

cursor_blink_interval 0

# BEGIN_KITTY_THEME
# Black Metal
include current-theme.conf
# END_KITTY_THEME
