# Foot terminal config
[main]
font=Mononoki Nerd Font:size=20
pad=2x2 center
resize-by-cells=no

[cursor]
style=block
blink=no

[colors-dark]
foreground=c1c1c1
background=030303
selection-foreground=030303
selection-background=121212

## Normal/regular colors (base16 0x08-0x0F)
regular0=030303
regular1=82709C
regular2=d1a76b
regular3=A1955F
regular4=696969
regular5=999999
regular6=aaaaaa
regular7=c1c1c1

## Bright colors
bright0=333333
bright1=82709C
bright2=d1a76b
bright3=A1955F
bright4=696969
bright5=999999
bright6=aaaaaa
bright7=c1c1c1
