# Foot terminal config
[main]
font=SFMono Nerd Font:size=18.9
#font=Maple Mono NF:size=18.9
pad=13x15 center
resize-by-cells=no
include=~/.config/foot/themes/rose-pine

[cursor]
style=block
blink=no

[colors-dark]
alpha=1.0
